import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Nunito} from "next/font/google"
import Navbar from './components/Navbar/Navbar'
import ClientOnly from './components/ClientOnly'
import RegisterModal from './components/modals/RegisterModal'
import ToasterProvider from './providers/ToasterProvider'
import LoginModal from './components/modals/LoginModal'
import getCurrentUser from './actions/getCurrentUser'
import RentModal from './components/modals/RentModal'

const inter = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Airbnb',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
        <ToasterProvider/>
        <LoginModal/>
        <RegisterModal />
        <RentModal/>
        </ClientOnly>
        <Navbar currentUser={currentUser}/>
        <div className='pb-20 pt-28'>
            {children}
        </div>
      </body>
    </html>
  )
}
